# Tells Nginx which Linux user to run worker processes as
# WordPress files are owned by www-data, so Nginx must run as www-data to access them safely
user www-data;

# Number of workwe processes Nginx will create a new process
# auto: one worker per CPU core
# Efficient and safe default
worker_processes auto;

# Location where Mginx stores its PID
# Used internally to manage the master process i.e. reload, stop, etc
pid /run/nginx.pid;

# Event handling for connections
events {
	# Defines how many connections each worker can handle
	# 1024 = max simultaneous connections per worker
	worker_connections 1024;
}

# HTTP configuration block
# Everything related to HTTP/HTTPS traffic lives inside this block
http {
	# SSL settings - To enable secure connections
	ssl_protocols TLSv1.2 TLSv1.3;

	# Loads file type mappings
	include mime.types;

	# Prefered server ciphers
	# Security best practice. Forces client to use the server's strong encryption methods
	ssl_prefer_server_ciphers on;

	# Fallback MIME type if a file extension isn't recognised
	default_type application/octet-stream;

	# Enables efficient file transfer using Linux kernel
	# Improves performance when serving static files (images, CSS)
	sendfile on;

	# HTTPS Server Block
	server {
		# Nginx can be accessed by port 443 only
		# ssl enables TLS
		listen 443 ssl;

		# Domain name this server responds to
		server_name muhabin-.42.fr;

		# TLS/SSL configuration
		# Path to my public certificate and private key
		ssl_certificate	 /etc/nginx/ssl/muhabin-.crt;
		ssl_certificate_key /etc/nginx/ssl/muhabin-.key;

		# directory where Nginx looks for website files
		root /var/www/html;

		# INDEX: default files to serve
		# Defines priority
		index index.php index.html index.htm;

		# Main entry point for requests
		location / {
			# $uri: try to serve the request as a file
			# $uri/: try to serve it as a directory
			# /index.php$is_args$args: forward request to index.php and preserve query parameters
			try_files $uri $uri/ /index.php$is_args$args;
		}

		location /site {
			# "website" is the Docker service name
			# proxy_pass: forward it to another server
			proxy_pass http://website:80/;
		}

		location /adminer {
			proxy_pass http://adminer:8080/;
		}

		# PHP execution via PHP-FPM
		# This vlock handles only PHP files
		location ~ \.php$ {
			# It telles PHP which file to execute and how
			include snippets/fastcgi-php.conf;

			# fastcgi_pass: telles Nginx send PHP requests to PHP-FPM
			# Nginx can talk to WordPress
			# no link, no host network
			fastcgi_pass wordpress:9000;
		}
	}
}
